name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: Library/
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

