name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - Android # Build an Android .apk standalone app.
        projectPath:
          - ./
        testMode:
          - playmode
          - editmode
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: Library/
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

