name: Test project

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: game-ci/unity-test-runner@v2
        with:
          projectPath: path/to/your/project
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
